"""Phase 0 package. Audit only — no feature extraction or modeling."""

from .catalog import (
    EXPECTED_JOINT_ANGLE_COUNT,
    EXPECTED_JOINT_CENTER_COUNT,
    EXPECTED_MARKER_COUNT,
    EXPECTED_NON_VICTIMIZED,
    EXPECTED_SAMPLING_HZ,
    EXPECTED_SUBJECTS,
    EXPECTED_VICTIMIZED,
    EXPECTED_WALKING_SIGNAL_COUNT,
    EXPECTED_WALKING_TRIALS,
)

__all__ = [
    "EXPECTED_SUBJECTS",
    "EXPECTED_VICTIMIZED",
    "EXPECTED_NON_VICTIMIZED",
    "EXPECTED_WALKING_TRIALS",
    "EXPECTED_SAMPLING_HZ",
    "EXPECTED_WALKING_SIGNAL_COUNT",
    "EXPECTED_MARKER_COUNT",
    "EXPECTED_JOINT_ANGLE_COUNT",
    "EXPECTED_JOINT_CENTER_COUNT",
]
